parameters: {}
environment:
  DATABASE_URL: ${DATABASE_URL}
packages:
    - name: phronesis
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: connect
          binary: false
          main: ""
          runtime: go:default
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
